- README.md
- docker-compose.yaml
- dockerfiles/api.Dockerfile
- event.json
- go.mod
- go.sum
- main.go
- sam_cli_entrypoint.sh
- template.yaml
The PR establishes the baseline implementation of a HelloWorld AWS Lambda running in the Go runtime. It creates a simple APIProxyGateway that responds to requests at localhost:3001. The implementation serves to isolate the container run by AWS SAM cli within another docker container. The purpose of nesting the Docker containers is to integrate the Go Lambda API with docker compose. This feature will allow easier startup of future AWS backend services through the docker compose command. 
The api.Dockerfile was updated to include the Go runtime in the container for future testing. It also circumvents a volume mounting issue that arises with the combination of a build stage and docker compose volume of the PWD. The docker compose command will generate the appropriate Golang binary for the …
> Setup of Go Lambda Environment for AWS with SAM cli

- .github/workflows/deploy-prod.yml
- functions/lambda/main.go
This PR fixes a few problems in the github actions `deploy-prod.yml` setup. 
We finally have a successful deployment on the books here: 
https://github.com/meetnearme/api/actions/runs/7767926053
> Fix GitHub actions deploy

- .github/workflows/remove-feature.yml
This is the annoying process of debugging github actions, I have to merge this to see the contents of the `if` condition after deleting a branch. Self-merging for this reason, the changed file is broken and does nothing right now anyway
> echo vars from the `if` condition to verify they are what I think they are

- .github/workflows/remove-feature.yml
This is the annoying process of debugging github actions, I have to merge this to see the contents of the if condition after deleting a branch. Self-merging for this reason, the changed file is broken and does nothing right now anyway
> SST stack deletion github action debugging

- .github/workflows/remove-feature.yml
self-merging because github actions `if` condition
> fix github expression syntax in remove-feature.yml workflow

- .github/workflows/remove-feature.yml
more attempts at fixing this workflow blindly, `if` condition should be fixed, self-merging to validate
> Fix SST deletion workflow on branch deletion

- .github/workflows/remove-feature.yml
self-merging as this is just blind debugging iteration without a way to simulate github actions in a virtual environment
> Fix syntax for Github Actions for specifying `main` checkout to pull in SST via npm

- .github/workflows/remove-feature.yml
self-merging, iteration is the only way in the absence of github actions debugging methods
> add missing permissions for AWS OIDC to SST remove feature workflow

- .github/workflows/check-todos.yml
- .github/workflows/deploy-dev.yml
- functions/gateway/helpers/db_helpers.go
I'm going to self-merge this first one, only because it simply adds the `TODO:` search github actions check that I want us to all standardize on as we will be moving starting quite soon
> Merge Back `develop` => `main`

- functions/gateway/handlers/page_handlers.go
- functions/gateway/handlers/page_handlers_test.go
Small clean up for develop branch before promoting to main.
> fix(go_lambda_test_coverage): remove bypass auth attempted work around

- functions/gateway/handlers/data_handlers.go
- functions/gateway/handlers/data_handlers_test.go
- functions/gateway/handlers/dynamodb_handlers/purchasables_handlers.go
- functions/gateway/handlers/page_handlers.go
- functions/gateway/handlers/page_handlers_test.go
- functions/gateway/handlers/partial_handlers.go
- functions/gateway/helpers/utils_test.go
- functions/gateway/services/dynamodb_service/purchases_service.go
- functions/gateway/services/marqo_service.go
- functions/gateway/services/marqo_service_test.go
- functions/gateway/templates/components/navbar.templ
- functions/gateway/templates/pages/event_details.templ
- functions/gateway/templates/pages/event_details_templ_test.go
Adding support for 
* checkout redirect in stripe
* `address` query param filter
> Short circuit checkout merge

- functions/gateway/templates/components/navbar.templ
- functions/gateway/templates/pages/event_details.templ
- functions/gateway/templates/pages/layout.templ
(event name limit = 50 chars, but yields silent API failure https://github.com/umami-software/umami/issues/2986)
> fix umami clickstream events 

- functions/gateway/helpers/utils.go
- functions/gateway/templates/components/navbar.templ
- functions/gateway/templates/pages/event_details.templ
- functions/gateway/templates/pages/home.templ
- functions/gateway/templates/pages/layout.templ
... finishing touches for now...
> "Add to Calendar" functionality, add RSVP / ICMI beacon handling / tracking, cleanup empty events list view

- functions/gateway/helpers/utils.go
- functions/gateway/templates/pages/event_details.templ
- functions/gateway/templates/pages/home.templ
- functions/gateway/templates/pages/layout.templ
Add top loading bar for more native app feel with MPA app, fix RSVP Google Calendar link timing (note that time is off in the database timestamp values, TODO: fix that)
> UI fix: RSVP event timestamp + Top loading bar

- functions/gateway/helpers/utils_test.go
Notably these issues only reveal themselves in CI runs, never in local test runs
> [fix] attempting to fix more port concurrency conflicts in tests

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-feature.yml
- .github/workflows/deploy-prod.yml
> [release] [fix] Fix event series child checkout bug with fetching wrong purchasables

- functions/gateway/handlers/page_handlers.go
- functions/gateway/templates/pages/layout.templ
> [release] Community / user page subdomains

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-feature.yml
- .github/workflows/deploy-prod.yml
per https://github.com/cloudflare/wrangler-action/issues/311
> Fix wrangler deployments 

- functions/gateway/handlers/data_handlers.go
- functions/gateway/handlers/dynamodb_handlers/competition_config_handlers.go
- functions/gateway/helpers/utils.go
- functions/gateway/templates/pages/competition_add_edit.templ
Bugfix: can't use double quote `"` characters in team names (move to JSON marshaling), bugfix: fix inverted logic for empty competitiorA / competitorB toast error
> [bugfix] double quote team names + logic inversion for competitor A / B empty value error toast

- functions/gateway/templates/pages/home.templ
> [fix] Improve visible of "voting open" indicator

- functions/gateway/handlers/auth_handlers.go
- functions/gateway/main.go
- functions/gateway/services/auth_service.go
> [release] Fix cookie issues with login / logout 

- functions/gateway/handlers/dynamodb_handlers/purchase_handlers.go
- functions/gateway/handlers/page_handlers.go
- functions/gateway/handlers/page_handlers_test.go
- functions/gateway/handlers/partial_handlers.go
- functions/gateway/helpers/constants.go
- functions/gateway/helpers/utils.go
- functions/gateway/services/dynamodb_service/competition_round_service.go
- functions/gateway/services/dynamodb_service/purchases_service.go
- functions/gateway/services/geo_service.go
- functions/gateway/services/marqo_service.go
- functions/gateway/services/marqo_service_test.go
- functions/gateway/templates/components/dropdown_nested_checkbox.templ
- functions/gateway/templates/components/navbar.templ
- functions/gateway/templates/pages/competition_add_edit.templ
- functions/gateway/templates/pages/event_add_edit.templ
- functions/gateway/templates/pages/event_add_edit_templ_test.go
- functions/gateway/templates/pages/home.templ
- functions/gateway/templates/pages/home_templ_test.go
- functions/gateway/templates/pages/layout.templ
- functions/gateway/templates/partials/events_admin_children.templ
- go.mod
- go.sum
- tailwind.config.js
Release contents: 
* #366 
* #367
* #368
* #369
* #370
* #371
* #372
* #373
* #374
* #377
> [release] Refactor filters, geocoordinate handling, add `radius` UI filter

- functions/gateway/templates/pages/home.templ
Release contents:
* https://github.com/meetnearme/api/pull/380
> [release] release/2025 04 15 a - fix cloudflare geolocation default

- .github/workflows/go.yml
- functions/gateway/handlers/page_handlers.go
- functions/gateway/handlers/page_handlers_test.go
> [feature] Add caching for playwright

- functions/gateway/helpers/utils.go
- functions/gateway/services/dynamodb_service/competition_round_service.go
> Revert "[release] Add debugging for batch round updates"
