meetnearme/api

.github/workflows/deploy-prod.yml
package.json
stacks/DeployProd.ts

In this PR, I've followed the guidance in the following docs to setup github actions to deploy via SST 
The `on` trigger is scoped down to `on:push:branches: - main` so that only merges to `main` trigger a deploy
* https://docs.sst.dev/going-to-production
* https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
* https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html

Setup GitHub actions deploy

---

functions/lambda/dynamodb.go

the dynamodb table name has an implicit value `Events` that we want to control with a const / var of some kind, the remainder (the prefix bit) is an implicit part of the SST naming convention, we want to separate them

parameterize dynamodb table naem

---

.github/workflows/remove-feature.yml

Add `.github/workflows/remove-feature.yml` to enable auto-deletion of SST / AWS CloudFormation stacks that begin with `feature-*` when a branch of that name is deleted (a side effect of merge)
Note this is one of those PRs that has to merge and be in `main` in order for the `on: delete: branches: 'feature/**' to work. It could get messy if I don't know what I'm doing, but I think it might be lined up to work properly with what I have here already

Feature: Enable auto-deletion of SST / AWS CloudFormation stacks when the feature branch merges

---

.env.example
README.md

For devs setting up this repo for the first time, the instructions to link SST using AWS is missing important steps.
This PR adds instructions directly to the README and updates .env.example to be in-line with the instructions

Update SST setup instructions in the readme

---

.github/workflows/remove-feature.yml

self-merging once again, since there's no reasonable path for debugging github actions and hence it needs to merge to `main`

SST remove workflow: git clone repo and checkout main for sst binary

---

stacks/StaticSiteStack.ts

Using optional chaining here should be enough to fix. 
Fixes #27

Fix prop-drilling on `undefined` blocking auto-delete / cleanup of feature/* AWS envs

---

package-lock.json
package.json

It's (maybe) cool (sometimes definitely) that dependabot scans our repo automatically. 
This scan https://github.com/meetnearme/api/security/dependabot made me realize that we have a bunch of node deps from an old POC I did that is not used anywhere in code

Prune legacy node deps

---

schemas/event.schema.json
schemas/purchasable.schema.json
schemas/registrationFields.schema.json
schemas/shared.schema.json

I'm implementing Marqo, which means we want this data to be fast and light, focusing only on what we want to index on. Fortunately, both `purchasable` and also `registrationFields` are data calls that we can resolve async (either via HTMX on load, or via `templ` http streaming if Lambda API Gateway allows it) so we want to move those out.
Also some adjustments are made based on the following marqo index configuration:
```
{
"type": "structured",
"vectorNumericType": "float",
"model": "hf/bge-large-en-v1.5",
"normalizeEmbeddings": true,
"textPreprocessing": {
"splitLength": 2,
"splitOverlap": 0,
"splitMethod": "sentence"
},
"imagePreprocessing": {
"patchMethod": null
},
"annParameters": {
"spaceType": "prenormalized-angular",
"parameters": {
"efConstruction": 512,
"m": 16
}
}, …
```

Update schema to new marqo-indexed fields, move `purchasable` & `registrationFields` out of event schema

---

functions/gateway/handlers/data_handlers.go
functions/gateway/handlers/data_handlers_test.go
functions/gateway/handlers/page_handlers.go
functions/gateway/handlers/page_handlers_test.go
functions/gateway/handlers/partial_handlers.go
functions/gateway/main.go
functions/gateway/services/marqo_service.go
functions/gateway/services/marqo_service_test.go
functions/gateway/services/marqo_service_types.go
functions/gateway/templates/pages/home.templ
static/assets/global.css

Introduce faceted serach via Marqo DB layer and query params for both the data API (used by The Regular) and also the home page event listing
* Add UI to browser events "this month" / "today" / "tomorrow" / "this week"
* Standardize / refactor to centralize query param and fallback search param logic decisions. Query capabilities
* lat / lon
* radius
* start / end time (with magic ranges `this_month` / `today` / `tomorrow` / `this_week`
* `q` (query) ... e.g `?q=organic`
* `ownerId` (not part of this PR, but added previously, still part of search facets)
https://www.youtube.com/watch?v=jaVUhrWABow
An example URL to play with:
https://devnear.me/?start_time=2024-09-15T18:30:00Z&end_time=2099-02-15T18:30:00Z&start_time=this_month&radius=3200

Feature/ Home Page Time Filters UI, Start / End Time query facets

---

functions/gateway/handlers/partial_handlers.go
functions/gateway/helpers/constants.go
functions/gateway/main.go
functions/gateway/services/auth_service.go
go.mod
go.sum

This PR adds authentication for zitadel service accounts to allow machine to machine access for data APIs
Use this guide to create a service user and get private key (key.json) file for the account. The corresponding public key is stored in zitadel: https://zitadel.com/docs/guides/manage/console/users
- Install zitadel-tools: Run `go install github.com/zitadel/zitadel-tools@latest`
- Generate a JWT: Run `zitadel-tools key2jwt --audience=https://meet-near-me-production-8baqim.zitadel.cloud --key=key.json`
- Get a signed JWT using the zitadel token endpoint
- Make a POST request to: `https://meet-near-me-production-8baqim.zitadel.cloud/oauth/v2/token`
- Set body as `x-www-form-urlencoded`
- Set `grant_type` to `urn:ietf:params:oauth:grant-type:jwt-bearer`
- Set `scope` to `openid profile …

Added service user middleware for data APIs

---

postcss.config.js

Store the hashed value of `layout.templ`'s content to guard against infinite loop in PostCSS watcher

[fix] PostCSS watcher fix - guard against infinite loop triggered from changes to `layout.templ`

---

functions/gateway/services/geo_service.go

fix scraping bee dom path `#mapDiv div div` has issues with string escaping and `js_render` needs to be set to true

[fix] failing geolocation field in production

---

functions/gateway/handlers/dynamodb_handlers/competition_config_handlers.go
functions/gateway/services/dynamodb_service/competition_round_service.go

Previously a dynamo error would be thrown about "batch write update failed" when an empty array slice was passed to `UpdateCompetitionConfig` handler was called with empty array `[]`

[fix] Allow empty competition rounds

---

functions/gateway/services/auth_service.go

The theory is that introducing this may have caused fallback behavior / which means the user's path isn't maintained after login
https://discord.com/channels/1096208627192320030/1151217204126290011/1338630571869339680

[bug] revert subdomain auth support, not supported with zitadel

---

functions/gateway/templates/pages/event_add_edit.templ
functions/gateway/templates/partials/events_admin_children.templ

Prior to this, new round associations would fail due to issues with prop drilling on undefined object properties
More significantly, this PR addresses issues where `event` <> `competition round` associations would only work by adding to the change queue rather than properly reconciling scoped (to selected `eventId` in the modal) changes that allow you to un-associate a round. 
This screenshot documents the intended working behavior for moving rounds, reconciling competition between different events for competition round association, and how to move competition rounds from one event to another

[fix] round association on event admin 

---

functions/gateway/handlers/auth_handlers.go
functions/gateway/main.go
functions/gateway/services/auth_service.go

This fixes an issue where users could get stuck in a redirect loop due to the invalid legacy tokens prior to the subdomain / logout fix here:
* #338
* #339
* #340
⚠️  NOTE ⚠️  Some places in code still show `access_token`/`refresh_token` because the underlying exchange with Zitadel assumes that keyname

[fix] Migrate from `access_token` / `refresh_token` ==> `mnm_access_token` /`mnm_refresh_token`

---

functions/gateway/handlers/auth_handlers.go
functions/gateway/main.go
functions/gateway/services/auth_service.go

Recursion, unfortunately. This PR reverts the previous reversion. On non-Chrome browsers, the login / logout behavior seems to be having issues with auto-logging people in, which isn't great. But after reverting #347, it's clear that this wrong behavior was there prior to #347
Reverts meetnearme/api#349

Revert "Revert "[release] Fix cookie issues with login / logout ""

---

functions/gateway/templates/pages/event_details.templ

Only show the loading indicator on event details page if rounds are loading / in flight

---

functions/gateway/types/competitions.go

Since Dynamo indexes on `endTime` for competition configs, we need to enforce that all competitions to be saved must have an end time

[fix] Require `endTime` for all competitions

---

functions/gateway/helpers/utils.go

Previous hotfix #398 outputs bytes without converting them to human readable, this PR fixes that

[hotfix] improve error handling for mnm cloudflare options put call
